version: '2.1'

services:
  postgres:
    image: postgres:13
    container_name: imdb_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imdb
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none
    restart: always

  postgres-init:
    image: postgres:13
    container_name: imdb_postgres_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=postgres
      - MINIMAL_DATASET_SIZE=100
      - RELOAD_DATASET=true
    volumes:
      - ./postgres-init/initialize-imdb.sh:/initialize-imdb.sh
      - ./postgres-init/data-cleanup.sh:/data-cleanup.sh
      - ./postgres-init/rid-missing.sc:/rid-missing.sc
      - ./postgres-init/schemas/schema.sql:/schema.sql
      - ./postgres-init/schemas/denormalized-schema.sql:/denormalized-schema.sql
      - ./postgres-init/schemas/minimal-schema.sql:/minimal-schema.sql
    command: bash -c "sleep 10 && /initialize-imdb.sh"

  pgadmin:
    image: dpage/pgadmin4
    container_name: imdb_pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    logging:
      driver: none

  neo4j:
    image: neo4j:latest
    container_name: imdb_neo4j
    ports: 
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - $HOME/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/plugins:/plugins
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
      # - NEO4J_AUTH=neo4j/imdb
      - NEO4J_AUTH=none
    networks:
      - default
    restart: always

  neo4j-init:
    build: ./neo4j-init
    container_name: neo4j_init
    depends_on: 
      - neo4j
    environment: 
      - NEO4J_HOSTNAME=neo4j
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
    networks:
      - default

  graphql:
    build: ./graphql-api-server
    container_name: imdb_graphql
    depends_on:
      - neo4j
    environment:
      - NEO4J_HOSTNAME=neo4j
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
      # - NEO4J_USER=neo4j
      # - NEO4J_PASSWORD=imdb
    ports:
      - "4000:4000"
    networks:
      - default
    restart: always
