version: '2.1'

services:
  neo4j:
    image: neo4j:latest
    container_name: imdb_neo4j
    ports: 
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - $HOME/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/plugins:/plugins
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
      # - NEO4J_AUTH=neo4j/imdb
      - NEO4J_AUTH=none
    networks:
      - default
    restart: always

  neo4jinit:
    build: ./neo4j-init
    container_name: neo4j_init
    depends_on: 
      - neo4j
    environment: 
      - NEO4J_HOSTNAME=neo4j
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
    networks:
      - default

  graphql:
    build: ./graphql-api-server
    container_name: imdb_graphql
    depends_on:
      - neo4j
    environment:
      - NEO4J_HOSTNAME=neo4j
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
      # - NEO4J_USER=neo4j
      # - NEO4J_PASSWORD=imdb
    ports:
      - "4000:4000"
    networks:
      - default
    restart: always
